import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { McLaren } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";




const mclaren=McLaren({
  variable: "--font-mclaren",
  subsets: ["latin"],
  weight: ["400"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mclaren.variable} `}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

